<?php if($this->isAllowed('form')): ?>	
	<div class="right"><?php echo $this->ajax("new", 'glossary/index/form/', 3); ?></div>
<?php endif; ?>	
<div class="left">
    <form id="formFindGlossary" action="#">
        <input type="text" name="q" id="qGlossary" style="width: 16em" />
        <input class="btn" type="submit" value="ok" /> &nbsp;&nbsp;&nbsp;
    </form>
</div>
<div class="clear">
    <?php echo $this->ajax('0-9', 'glossary/index/index/q/%5B0-9%5D'); ?>

    <?php foreach( range( 'a' , 'z' ) as $letter ): ?>
        <?php echo $this->ajax(strtoupper($letter), 'glossary/index/index/q/' . base64_encode($letter) ); ?>
    <?php endforeach; ?>
    <?php echo $this->ajax('all', 'glossary/index/index/q/'); ?>
</div>
<br />
<?php if (count($this->data)):?>
    <table class="zebra-striped">
        <?php foreach ($this->data as $key => $data): ?>
            <?php
                $display = "display: none;";
                if ($this->q && (strlen($this->q) > 1) && $key == 0) {
                    $display = null;
                }
            ?>
            <tr>
                <td>
                    <a class="glossary-show" href="#" target="#g<?php echo $data->id?>"><?php echo $data->word?></a>
                    <div style="<?php echo $display?> margin-top: 10px;" id="g<?php echo $data->id?>"><?php echo nl2br($data->description)?></div>
                </td>
                <td class="aright" nowrap="nowrap">
                    <?php if ($this->isAllowed('form')): ?>
                        <?php echo $this->ajax("edit", 'glossary/index/form/id/'. $data->id, 2); ?>
                    <?php endif;?>

                    <?php if($this->isAllowed("delete")): ?>
                        <?php echo $this->ajax("delete", 'glossary/index/delete/id/' . $data->id, 2 , "want to delete?");?>
                    <?php endif;?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
    <div id="glossary-page">
        <?php echo $this->paginationControl($this->data) ?>
    </div>
<?php else:?>
    <p><?php echo $this->translate( "there are no records" );?></p>
<?php endif;?>
<script type="text/javascript">
    $('.glossary-show').click(function(){
        $(this.target).toggle();
        return false;
    });

    $('#glossary-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });

    $("#formFindGlossary").submit(function(ev) {
		$(this).parents('.content').load('glossary/index/index/text/' + $('#qGlossary').val());
        return false;
	});

    
</script>